networks:
  rdconversas:
    driver: bridge

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - rdconversas

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - rdconversas

  boilerplate-go:
    build:
      context: .
      dockerfile: .docker/dockerfiles/Dockerfile
    entrypoint: ["bash", "./.docker/entrypoints/entrypoint-dev.sh"]
    container_name: boilerplate-go
    restart: always
    ports:
      - 9001:9001
    volumes:
      - .:/usr/boilerplate-go/app
    environment:
      PORT: 9001
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URI: mongodb://mongodb/boilerplate
    networks:
      - rdconversas

volumes:
  mongodb_data:
    driver: local
  cache:
    driver: local
